### ISSUE TITLE
Is "not suitable for upgrading many clients simultaneously" still valid?

### ISSUE THREAD

**Issue by davidpaMSFT** [Microsoft/SCCMdocs#1086]
I think this is no longer the case as we “recommend that you enable automatic client upgrades across your hierarchy” as per here: https://docs.microsoft.com/en-us/sccm/core/clients/manage/upgrade/upgrade-clients-for-windows-computers#use-automatic-client-upgrade

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c2427b8-6860-dbb1-9ef1-4444d0a72de2
* Version Independent ID: 860c0144-916c-318c-2577-22ea331559d1
* Content: [Upgrade clients - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/upgrade/upgrade-clients#feedback)
* Content Source: [sccm/core/clients/manage/upgrade/upgrade-clients.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/upgrade/upgrade-clients.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @davidpaMSFT, I was just about to respond to your email. 😄 
Correct. Because of the randomization over the specified period, only auto-upgrade is suitable for large-scale client upgrades. Push is too slow on large scale. GPO/WSUS don’t have randomization. We should remove the following line from this article: `not suitable for upgrading many clients simultaneously`

Note: Client piloting isn’t good for large scale as it doesn’t randomize at all.

**Comment by aczechowski** [comment]
Another good one for community to help with. Marking for help-wanted. [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute)
